In [3]:
'''
Demo of data prepossessing
'''
# Importing the libraries
import numpy as np
import pandas as pd

# Importing dataset
dataset = pd.read_csv("Data.csv")
# iloc[row index, column index]
X = dataset.iloc[: , :-1].values # :-1 returns all elements except the last one
Y = dataset.iloc[: , 3].values
print(X)
print(Y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [4]:
# Handling the missing data with mean
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = "NaN", strategy = "mean", axis = 0)
imputer = imputer.fit(X[ : , 1:3])
X[ : , 1:3] = imputer.transform(X[ : , 1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [6]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[ : , 0] = labelencoder_X.fit_transform(X[ : , 0])
print(X)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [8]:
# Creating a dummy variable
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()
labelencoder_Y = LabelEncoder()
Y =  labelencoder_Y.fit_transform(Y)
print(X)
print(Y)

[[0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  4.40000000e+01 7.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  2.70000000e+01 4.80000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  3.00000000e+01 5.40000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  3.80000000e+01 6.10000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  4.00000000e+01 6.37777778e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  3.50000000e+01 5.80000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  3.87777778e+01 5.20000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  4.80000000e+01 7.90000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  5.00000000e+01 8.30000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  3.70000000e+01 6.70000000e+04]]
[0 1 0 0 1 1 0 1 0 1]


In [0]:
#Splitting the datasets into training sets and Test sets
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split( X , Y , test_size = 0.2, random_state = 0)

In [11]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)
print(X)
print(Y)

[[0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  4.40000000e+01 7.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  2.70000000e+01 4.80000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  3.00000000e+01 5.40000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  3.80000000e+01 6.10000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  4.00000000e+01 6.37777778e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  3.50000000e+01 5.80000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  3.87777778e+01 5.20000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  4.80000000e+01 7.90000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  5.00000000e+01 8.30000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  3.70000000e+01 6.70000000e+04]]
[0 1 0 0 1 1 0 1 0 1]
